### ISSUE TITLE
Allow fetch_new_version() and fetch_info() to be overridden

### ISSUE THREAD

**Issue by tollmanz** [cftp/external-update-api#6]
Removing `final` from the definition of `fetch_new_version()` and `fetch_info()` would allow for alternate plugin/theme information discovery methods. In particular, this is useful for situations where the plugin/theme file is not publicly accessible. I am hoping to use a feed of plugin and theme information to broadcast update availability and would like to override these functions to provide the alternate method.

Any problems in removing those two `final` declarations?

**Comment by johnbillion** [comment]
It sounds like the class you're writing should extend the base `EUAPI_Handler` class rather than `EUAPI_Handler_Files`. The latter is specifically for plugin/theme updates which are fetched by reading the plugin or theme file from a URL.

If you extend `EUAPI_Handler` instead, `fetch_new_version()` and `fetch_info()` are abstract methods that you'll need to define.

How does that sound?

**Comment by tollmanz** [comment]
Yeah...that makes sense. I was working off of the Github handler example as I got my head wrapped around this a bit. I think that makes perfect sense though. Thanks!
